# Generated by Django 4.2.7 on 2023-11-20 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cad_campanhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campanhas',
            },
        ),
        migrations.CreateModel(
            name='cad_cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='cad_polos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'polos',
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('area_code', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=9)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'consultor',
            },
        ),
        migrations.CreateModel(
            name='tipo_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_concurso', models.IntegerField(choices=[(51, '51'), (52, '52'), (53, '53'), (54, '54')], null=True)),
                ('ano_concurso', models.IntegerField(null=True)),
                ('data_matricula', models.DateField()),
                ('nome_aluno', models.CharField(max_length=200)),
                ('numero_ra', models.CharField(max_length=12)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_polo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('desconto_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('pontos_trocados', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('active', models.BooleanField(default=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_campanhas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_cursos')),
                ('tipo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.tipo_curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
    ]
