# Generated by Django 4.2.7 on 2023-11-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='usuario',
        ),
    ]
