# Generated by Django 4.2.7 on 2023-11-28 22:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='curso',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tipo_curso', chained_model_field='tipo_curso', on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_cursos'),
        ),
    ]
