# Generated by Django 4.2.7 on 2023-11-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_alter_matriculas_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_cursos'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='tipo_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matriculas.tipo_curso'),
        ),
    ]
