# Generated by Django 4.2.7 on 2023-11-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_matriculas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='pontos',
        ),
    ]
