# Generated by Django 4.2.7 on 2023-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_alter_matriculas_curso_alter_matriculas_tipo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(choices=[('U', 'USUARIO'), ('A', 'ADMINISTRADOR')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
