# Generated by Django 4.2.7 on 2023-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_remove_matriculas_pontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='data_matricula',
            field=models.DateTimeField(),
        ),
    ]
