# Generated by Django 4.2.7 on 2023-12-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_delete_consultor_alter_matriculas_desconto_polo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='desconto_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
