# Generated by Django 4.2.7 on 2023-11-21 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0005_alter_matriculas_data_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad_polos',
            name='users',
            field=models.ManyToManyField(related_name='polos', to=settings.AUTH_USER_MODEL),
        ),
    ]
