# Generated by Django 4.2.7 on 2023-12-11 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0006_alter_matriculas_desconto_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
    ]
