# Generated by Django 4.2.7 on 2023-11-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cad_processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.IntegerField(choices=[(51, '51'), (52, '52'), (53, '53'), (54, '54')], null=True)),
                ('ano_processo', models.IntegerField()),
                ('data_inicial_processo', models.DateTimeField()),
                ('data_final_processo', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'processo',
            },
        ),
    ]
