# Generated by Django 4.2.7 on 2023-11-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_cad_processo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='ano_concurso',
        ),
        migrations.RemoveField(
            model_name='matriculas',
            name='numero_concurso',
        ),
        migrations.AddField(
            model_name='matriculas',
            name='processo_sel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_processo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cad_processo',
            name='numero_processo',
            field=models.IntegerField(null=True),
        ),
    ]
