# Generated by Django 4.2.7 on 2023-11-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_remove_matriculas_ano_concurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_processo',
            name='ano_processo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='cad_processo',
            name='numero_processo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
